pocketpy/pocketpy

README.md
Changing byterun reference in README (english) to point to Allison Kaptur's original AOSA article.
=> Update byterun link in README

src/main.cpp
Without this, `std::getline` fails silently and this loops infinitely printing the prompt.
=> Allow using Ctrl-D to quit the REPL

src/builtins.h, tests/_builtin_ty.py
Add `any` and `all` functions to `builtins`
Follows implementation details from Python3 documentation:
https://docs.python.org/3/library/functions.html#all
https://docs.python.org/3/library/functions.html#any
=> Add all, any builtins

src/compiler.h, src/error.h, src/vm.h, tests/_exception.py
Adds support for providing an optional message to an `assert`. A message is any `expr`. 
New behavior: 
```python3
>>> assert False, "Test"
Traceback (most recent call last):
File "<stdin>", line 1
assert False, "Test"
AssertionError: Test
>>> x = 1
>>> assert False, x
Traceback (most recent call last):
File "<stdin>", line 1
assert False, x
AssertionError: 1
>>> assert False, ""
Traceback (most recent call last):
File "<stdin>", line 1
assert False, ""
AssertionError
```
The last example follows Python's behavior. 
I'm not sure if the changes in `compiler.h` are acceptable, I am still trying to get familiar with this codebase. 
Also, I am not sure where the best place is for tests for this.
=> Assert with message

c_bindings/pocketpy_c.cpp, c_bindings/test.c, c_bindings/test_answers.txt
exceptions are currently brittle in their implemenation, there are some uses cases that are not support when throwing exceptions from python and passing through c code.
However the current implementation as it stands will work for the TIC-80 bindings I am working on since they only require fairly shallow bindings without nesting python and c code many times recursively.
I added a test cases that you can uncomment to demonstrate where it breaks, and if a real world project ever needs that functionality we can work out a way to support those cases.
=> adjusted exceptions to be back to using Exception in c bindings

c_bindings/pocketpy_c.cpp
these are the last changes I made to make the initial bindings for tic80. If we ever get the exceptions better supported these checks can probably be removed
=> added check on to_type methods so that they will not cause a crash when type is wrong

.gitignore, plugins/flutter/src/pocketpy.h
Flutter plugin version 0.9.3 on pub.dev doesn't include `pocketpy.h` header file when installed through `flutter pub add pocketpy`. At some point, this file has been added to gitignore so it wasn't pushed to pub.dev. 
This PR removes the ignore and adds the header source file from the releases (0.9.3 version).
=> Fix-Flutter/source file missing lts

python/builtins.py
To test my implementation, I followed the following steps:
1. Build the project using cmake
2. Using the generated `main` executable, test the following:
```python
print('We are the {} who say "{}!"'.format('knights', 'Ni'))
print('{0} and {1}'.format('spam', 'eggs'))
print('{1} and {0}'.format('spam', 'eggs'))
print('This {food} is {adjective}.'.format(food='spam', adjective='absolutely horrible'))
```
P.S. I am entirely new at contributing to open-source projects. Please guide me if I have made any mistakes.
=> Added better string formatting as required by Issue#138

build.sh, include/pocketpy/lexer.h, prebuild.py, src/lexer.cpp, src/pocketpy.cpp, tests/01_int.py
This small PR adds support for octal literals such as `0o1234`. Commonly used in Linux filesystem permission bits such as `0o644` and `0o777`.
This also adds support for binary literals such as `0b10010`
=> Added support for octal and binary literals

include/pocketpy/export.h, include/pocketpy/pocketpy_c.h
to avoid on recent emsdk (clang upstream)
```
In file included from /opt/python-wasm-sdk/emsdk/upstream/emscripten/cache/sysroot/include/emscripten/emscripten.h:23:
/opt/python-wasm-sdk/emsdk/upstream/emscripten/cache/sysroot/include/emscripten/em_asm.h:151:1: error: templates must have C++ linkage
151 | template<typename, typename = void> struct __em_asm_sig {};
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> ensure em_asm template get C++ linkage ( cmake builds )

README.md, README_zh.md, docs/quick-start/installation.md
A minor change to the example in the README files. I believe it shouldn't have any blockers. Thanks !
Example (Main) - 
```
C:\Users\kunni\pocketpy>try.exe
Hello world!
610
```
Example (Branch) - 
```
C:\Users\kunni\pocketpy>try.exe
Hello world!
Sum of the list: 6
Sum of 2 variables: 10
```
=> Improve readability of example code

src/pocketpy.cpp, tests/04_str.py
A TypeError is raised when the length of the fillchar parameter is not equal to 1.
=> Check the size of fillchar passed to str methods (ljust, rjust)

src/pocketpy.cpp, src/str.cpp, tests/04_str.py
The current str.find doesn't perform boundary checks, which can lead to a crash or even security issues. 
A simple way to reproduce this bug: "hello".find('lo', -100000)
Instead, -1 should be returned in this case.
=> Perform boundary checks before searching to prevent security vulnerabilities

include/pocketpy/vector.h
I fixed a small typo that produced an error when compiling WASM for the [TIC-80](https://github.com/nesbox/TIC-80) project
=> Emscripten build fix

.github/workflows/main.yml
> actions/upload-artifact@v3 is scheduled for deprecation on **November 30, 2024**. [Learn more.](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)
> Similarly, v1/v2 are scheduled for deprecation on **June 30, 2024**.
> Please update your workflow to use v4 of the artifact actions.
> This deprecation will not impact any existing versions of GitHub Enterprise Server being used by customers.
=> Update actions/upload-artifact to v4

src/interpreter/ceval.c, src/interpreter/vm.c
Hi!
I has some issues with this empty initializer on msvc 19.38 and earlier. Using -std=c11 -pedantic on gcc will also show a warning. Putting a 0 in there should do the same thing, and makes Visual Studio happy.
See https://godbolt.org/z/Y4zK578Ea
=> Fixes: warning: ISO C forbids empty initializer braces before C23

CMakeLists.txt, src/modules/os.c
before:
```text
[61/63] Building C object CMakeFiles/main.dir/src2/main.c.obj
C:/Users/Trim21/proj/pocketpy/src2/main.c:14:18: warning: 'fopen' is deprecated: This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [-Wdeprecated-declarations]
14 |     FILE* file = fopen(path, "rb");
|                  ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\stdio.h:212:20: note: 'fopen' has been explicitly marked deprecated here
212 |     _Check_return_ _CRT_INSECURE_DEPRECATE(fopen_s)
|                    ^
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\vcruntime.h:356:55: note: expanded from macro '_CRT_INSECURE_DEPRECATE'
356 | …
```
=> fix win32 clang build

src/modules/pickle.c
On windows **debug build** runtime will check sighed overflow and popup a window
=> avoid undefined behavior signed int overflow

3rd/numpy/tests/test_numpy.cpp, include/pybind11/internal/builtins.h, include/pybind11/internal/error.h, include/pybind11/internal/function.h, include/pybind11/tests/error.cpp
According to pybind11's [exception documentation](https://pybind11.readthedocs.io/en/stable/advanced/exceptions.html#handling-errors-from-the-python-c-api), you should be able to construct an `py::error_already_set` object with no arguments:
```cpp
py::set_error(PyExc_TypeError, "C API type error demo");
throw py::error_already_set();
```
We can't do this, because pocketpy's `py::error_already_set` is a type alias for `python_error`:
https://github.com/pocketpy/pocketpy/blob/697312cae5a886a533198e2c2457436c9eefb526/include/pybind11/internal/error.h#L28
https://github.com/pocketpy/pocketpy/blob/697312cae5a886a533198e2c2457436c9eefb526/include/pybind11/internal/error.h#L8-L11
This PR makes pocketpy's pybind11 implementation on par with the CPython reference.
Fixes: #319
=> fix pybind11 implementation for error_already_set

include/pybind11/internal/module.h, include/pybind11/tests/module.cpp
Adds `py::module` instance method `reload` as described [here](https://pybind11.readthedocs.io/en/stable/advanced/embedding.html#:~:text=Modules%20can%20be%20reloaded%20using%20module_%3A%3Areload()) based on the reference pybind11 implementation [here](https://github.com/pybind/pybind11/blob/945e251a6ce7273058b36214d94415e9c9530b8e/include/pybind11/pybind11.h#L1253-L1259).
=> add pybind11 implementation for module reload

src/interpreter/frame.c
When a trace function is set using `settrace`, we can access the current file name and line number through `py_Frame_sourceloc`. However, during function calls, the line number is returned as 0. This PR fixes this issue to return the correct line number.
=> Fix line number reporting in trace functions for function calls

.github/workflows/pybind11.yml
Since CMake is already pre-installed in the workflow environment and the version configuration may be outdated, this PR removes the unnecessary CMake installation step from the workflow configuration.
=> Remove redundant CMake setup steps in pybind11 workflow

.github/workflows/main.yml, CMakeLists.txt, include/pocketpy/common/socket.h, src/common/socket.c
Add a new socket module for pocketpy, providing an unified API for both Windows, Linux and MAC. But cannot support IOS and Android.
=> Add socket module for Linux and Windows
